### ISSUE TITLE
Start locatie

### ISSUE THREAD

**Issue by MvdZande** [VincentSmit/cappening#10]
Startlocatie is huidige locatie wanneer beschikbaar of laatste locatie van de device

**Comment by NLthijs48** [comment]
Gefixt in https://github.com/VincentSmit/cappening/commit/95c8aaba5c87d2be1956ff22e1d7cd02f8ebe0f6 Laatste locatie en zoomlevel worden lokaal opgeslagen, en worden later hersteld.
